//
//  OnboardingConfirmationView.swift
//  Alarmio
//
//  Created by Parenthood ApS on 4/2/26
//  Copyright © 2026 Parenthood ApS. All rights reserved.
//

import SwiftUI

/// Final step of onboarding. Identical shape to CreateAlarmView's
/// confirming phase — hero, then the same stack of alarm-preview / compact
/// voice / name / customize cards plus a regenerate button. The container
/// owns persistence; tapping Schedule flows back through the container's
/// scheduleAlarm().
struct OnboardingConfirmationView: View {

    // MARK: - Environment

    @Environment(OnboardingManager.self) private var manager
    @Environment(\.deviceInfo) private var deviceInfo
    @Environment(\.composerService) private var composerService
    @Environment(\.alarmStore) private var alarmStore
    @Environment(\.alertManager) private var alertManager

    // MARK: - State

    @State private var heroVisible = false
    @State private var checkVisible = false
    @State private var heroExited = false
    @State private var cardsVisible = false
    @State private var voicePlayer = VoicePreviewPlayer()
    @State private var voiceIndex: Int = 0
    @State private var isRegenerating: Bool = false
    @State private var showRegenSuccess: Bool = false
    @State private var regenSuccessTask: Task<Void, Never>?
    @State private var showNameSheet: Bool = false
    @State private var committed: AlarmConfiguration
    @State private var proToggle: Bool = false

    // MARK: - Constants

    let onSchedule: () -> Void
    let isScheduling: Bool

    // MARK: - Init

    init(onSchedule: @escaping () -> Void, isScheduling: Bool) {
        self.onSchedule = onSchedule
        self.isScheduling = isScheduling
        self._committed = State(initialValue: AlarmConfiguration())
    }

    // MARK: - Body

    var body: some View {
        ZStack {

            // Phase 1: Hero
            if !heroExited {
                heroView
            }

            // Phase 2: Same card stack as CreateAlarmView.confirmationCard
            if heroExited {
                detailView
                    .transition(.opacity)
            }
        }
        .task {
            // Seed committed from the manager's configuration — the audio
            // file has already been generated by the container and stored
            // on manager.configuration.soundFileName.
            committed = manager.configuration
            voiceIndex = heroVoices.firstIndex { $0.persona == manager.configuration.voicePersona } ?? 0
            await runEntrySequence()
        }
        .onDisappear {
            voicePlayer.stop()
            regenSuccessTask?.cancel()
        }
        .sheet(isPresented: $showNameSheet) {
            NameAlarmSheet(initialName: committed.name ?? "") { newName in
                let trimmed = newName.isEmpty ? nil : newName
                committed.name = trimmed
                manager.configuration.name = trimmed
            }
            .presentationDetents([.height(240)])
            .presentationDragIndicator(.visible)
            .presentationBackground(Color(hex: "0f1a2e"))
        }
    }

    // MARK: - Hero

    private var heroView: some View {
        VStack(spacing: 20) {

            Spacer()

            // Checkmark + title
            VStack(spacing: 0) {

                ZStack {
                    Circle()
                        .fill(Color(hex: "4AFF8E").opacity(0.08))
                        .frame(width: 80, height: 80)
                        .blur(radius: 16)

                    Image(systemName: "checkmark.circle.fill")
                        .font(.system(size: 44))
                        .foregroundStyle(Color(hex: "4AFF8E"))
                        .opacity(checkVisible ? 1 : 0)
                        .scaleEffect(checkVisible ? 1 : 0.5)
                        .animation(.spring(response: 0.5, dampingFraction: 0.7), value: checkVisible)
                }

                Text("Your alarm is ready")
                    .font(AppTypography.headlineLarge)
                    .tracking(AppTypography.headlineLargeTracking)
                    .foregroundStyle(.white)
            }
            .premiumBlur(isVisible: heroVisible, duration: 0.5)

            Spacer()
        }
    }

    // MARK: - Detail View (mirrors CreateAlarmView.confirmationCard)

    private var detailView: some View {
        ScrollView {
            VStack(spacing: AppSpacing.itemGap(deviceInfo.spacingScale)) {

                // Alarm audio preview
                alarmPreviewCard
                    .padding(.horizontal, AppSpacing.screenHorizontal)
                    .premiumBlur(isVisible: cardsVisible, delay: 0, duration: 0.5)

                // Compact voice selector
                compactVoiceCard
                    .padding(.horizontal, AppSpacing.screenHorizontal)
                    .premiumBlur(isVisible: cardsVisible, delay: 0.1, duration: 0.5)

                // Name row
                NameRowCard(name: committed.name, style: .clear) {
                    HapticManager.shared.softTap()
                    showNameSheet = true
                }
                .padding(.horizontal, AppSpacing.screenHorizontal)
                .premiumBlur(isVisible: cardsVisible, delay: 0.15, duration: 0.5)

                // Customize (no Pro row in onboarding)
                CustomizeCard(
                    tone: Bindable(manager).configuration.tone,
                    whyContext: Bindable(manager).configuration.whyContext,
                    intensity: Bindable(manager).configuration.intensity,
                    isProOn: $proToggle,
                    showProRow: false
                )
                .padding(.horizontal, AppSpacing.screenHorizontal)
                .premiumBlur(isVisible: cardsVisible, delay: 0.2, duration: 0.5)

                // Regenerate
                regenerateButton
                    .padding(.horizontal, AppSpacing.screenHorizontal)
                    .premiumBlur(isVisible: cardsVisible, delay: 0.25, duration: 0.5)

                Spacer(minLength: 0)
                    .frame(height: 20)
            }
            .padding(.top, 8)
        }
        .scrollIndicators(.hidden)
        .scrollBounceBehavior(.basedOnSize)
        .mask(scrollFadeMask)
    }

    // MARK: - Alarm Preview Card

    private var alarmPreviewCard: some View {
        let isPlaying = voicePlayer.isPlaying

        return VStack(spacing: 14) {

            Text("ALARM PREVIEW")
                .font(AppTypography.caption)
                .tracking(AppTypography.captionTracking)
                .foregroundStyle(.white.opacity(0.4))

            VoiceWaveform(bands: voicePlayer.bands, isPlaying: isPlaying)
                .frame(height: 40)
                .padding(.horizontal, 8)

            Button {
                HapticManager.shared.buttonTap()
                toggleAlarmPreview()
            } label: {
                HStack(spacing: 8) {
                    Image(systemName: isPlaying ? "stop.fill" : "play.fill")
                        .font(.system(size: 14))
                        .contentTransition(.symbolEffect(.replace))

                    Text(isPlaying ? "Stop" : "Play")
                        .font(AppTypography.labelMedium)
                        .contentTransition(.numericText())
                }
                .foregroundStyle(.white)
                .frame(height: 40)
                .frame(maxWidth: .infinity)
                .background(.white.opacity(0.12))
                .clipShape(Capsule())
            }
            .disabled(committed.soundFileName == nil || isRegenerating)
            .opacity(committed.soundFileName == nil ? 0.4 : 1)
            .animation(.spring(response: 0.3, dampingFraction: 0.85), value: isPlaying)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 16)
        .padding(.horizontal, 16)
        .glassEffect(.clear, in: RoundedRectangle(cornerRadius: 20))
    }

    // MARK: - Compact Voice Card

    private var compactVoiceCard: some View {
        let voice = heroVoices[voiceIndex]

        return HStack(spacing: 10) {

            Button {
                HapticManager.shared.selection()
                cycleVoice(by: -1)
            } label: {
                Image(systemName: "chevron.left")
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundStyle(.white.opacity(0.6))
                    .frame(width: 28, height: 28)
                    .background(.white.opacity(0.1))
                    .clipShape(Circle())
            }

            VStack(spacing: 2) {
                Text(voice.name)
                    .font(AppTypography.labelMedium)
                    .foregroundStyle(.white)
                    .contentTransition(.numericText())

                Text(voice.descriptor)
                    .font(AppTypography.caption)
                    .foregroundStyle(.white.opacity(0.35))
                    .contentTransition(.numericText())
            }
            .frame(maxWidth: .infinity)
            .animation(.spring(response: 0.3, dampingFraction: 0.85), value: voiceIndex)

            Button {
                HapticManager.shared.selection()
                cycleVoice(by: 1)
            } label: {
                Image(systemName: "chevron.right")
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundStyle(.white.opacity(0.6))
                    .frame(width: 28, height: 28)
                    .background(.white.opacity(0.1))
                    .clipShape(Circle())
            }
        }
        .padding(.vertical, 14)
        .padding(.horizontal, 16)
        .frame(maxWidth: .infinity)
        .glassEffect(.clear, in: RoundedRectangle(cornerRadius: 20))
    }

    // MARK: - Regenerate Button

    private var hasStyleChanges: Bool {
        manager.configuration.tone != committed.tone
            || manager.configuration.whyContext != committed.whyContext
            || manager.configuration.intensity != committed.intensity
            || manager.configuration.voicePersona != committed.voicePersona
    }

    private var draftIsReadyToGenerate: Bool {
        manager.configuration.tone != nil
            && manager.configuration.whyContext != nil
            && manager.configuration.intensity != nil
    }

    private var regenerateButtonLabel: String {
        if showRegenSuccess { return "Success" }
        if isRegenerating { return "Generating..." }
        return "Regenerate"
    }

    private var regenerateButtonForeground: Color {
        if showRegenSuccess { return Color(hex: "4AFF8E") }
        let active = hasStyleChanges && draftIsReadyToGenerate && !isRegenerating
        return .white.opacity(active ? 1 : 0.35)
    }

    private var regenerateButtonBackground: Color {
        if showRegenSuccess { return Color(hex: "4AFF8E").opacity(0.15) }
        let active = hasStyleChanges && draftIsReadyToGenerate
        return .white.opacity(active ? 0.1 : 0.04)
    }

    private var regenerateButton: some View {
        Button {
            HapticManager.shared.buttonTap()
            regenerateAlarm()
        } label: {
            HStack(spacing: 8) {
                if isRegenerating {
                    ProgressView()
                        .tint(.white)
                        .scaleEffect(0.8)
                } else if showRegenSuccess {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.system(size: 14, weight: .semibold))
                } else {
                    Image(systemName: "arrow.clockwise")
                        .font(.system(size: 14, weight: .medium))
                }

                Text(regenerateButtonLabel)
                    .font(AppTypography.labelMedium)
                    .contentTransition(.numericText())
            }
            .foregroundStyle(regenerateButtonForeground)
            .frame(height: 44)
            .frame(maxWidth: .infinity)
            .background(regenerateButtonBackground)
            .clipShape(Capsule())
            .overlay {
                if showRegenSuccess {
                    Capsule()
                        .strokeBorder(Color(hex: "4AFF8E").opacity(0.6), lineWidth: 1)
                }
            }
            .shadow(color: showRegenSuccess ? Color(hex: "4AFF8E").opacity(0.2) : .clear, radius: 12, y: 0)
        }
        .disabled(!hasStyleChanges || !draftIsReadyToGenerate || isRegenerating || showRegenSuccess)
        .animation(.easeInOut(duration: 0.35), value: showRegenSuccess)
        .animation(.easeInOut(duration: 0.25), value: isRegenerating)
    }

    // MARK: - Private Methods

    private func runEntrySequence() async {
        // 1. Hero blurs in
        try? await Task.sleep(for: .milliseconds(100))
        heroVisible = true

        // 2. Checkmark pops
        try? await Task.sleep(for: .milliseconds(250))
        checkVisible = true
        HapticManager.shared.success()

        // 3. Hold the hero
        try? await Task.sleep(for: .seconds(1.5))

        // 4. Blur hero out
        heroVisible = false

        // 5. Swap to cards
        try? await Task.sleep(for: .milliseconds(500))
        heroExited = true

        try? await Task.sleep(for: .milliseconds(100))
        cardsVisible = true
    }

    private func toggleAlarmPreview() {
        if voicePlayer.isPlaying {
            voicePlayer.stop()
        } else {
            guard let fileName = committed.soundFileName else { return }
            let url = alarmStore.audioFileManager.soundFileURL(named: fileName)
            voicePlayer.playFromFile(url: url, persona: committed.voicePersona)
        }
    }

    private func cycleVoice(by delta: Int) {
        let newIndex = (voiceIndex + delta + heroVoices.count) % heroVoices.count
        voiceIndex = newIndex
        manager.configuration.voicePersona = heroVoices[newIndex].persona

        // Preview playback is tied to the previously-generated file; stop
        // it so the user hits Regenerate to hear the new voice.
        voicePlayer.stop()
        invalidateRegenSuccess()
    }

    private func regenerateAlarm() {
        voicePlayer.stop()
        isRegenerating = true

        Task { @MainActor in
            do {
                guard let composerService else {
                    throw NSError(
                        domain: "ComposerService",
                        code: -1,
                        userInfo: [NSLocalizedDescriptionKey: "Composer service unavailable"]
                    )
                }

                let newFileName = try await composerService.generateAndDownloadAudio(
                    for: manager.configuration
                )
                manager.configuration.soundFileName = newFileName
                var next = manager.configuration
                next.soundFileName = newFileName
                committed = next

                isRegenerating = false
                HapticManager.shared.success()
                triggerRegenSuccess()
            } catch {
                isRegenerating = false
                print("[OnboardingConfirmationView] Regenerate failed: \(error)")
                let errorMessage = (error as? APIError)?.errorDescription
                    ?? "Please try again."
                alertManager.showModal(
                    title: "Regeneration failed",
                    message: errorMessage,
                    primaryAction: AlertAction(label: "OK") {}
                )
            }
        }
    }

    private func triggerRegenSuccess() {
        regenSuccessTask?.cancel()
        showRegenSuccess = true

        regenSuccessTask = Task { @MainActor in
            try? await Task.sleep(for: .milliseconds(1500))
            guard !Task.isCancelled else { return }
            showRegenSuccess = false
        }
    }

    private func invalidateRegenSuccess() {
        if showRegenSuccess {
            regenSuccessTask?.cancel()
            regenSuccessTask = nil
            showRegenSuccess = false
        }
    }

    // MARK: - Scroll Fade Mask

    private var scrollFadeMask: some View {
        VStack(spacing: 0) {
            LinearGradient(
                stops: [
                    .init(color: .clear, location: 0),
                    .init(color: .white, location: 1)
                ],
                startPoint: .top,
                endPoint: .bottom
            )
            .frame(height: 16)

            Color.white

            LinearGradient(
                stops: [
                    .init(color: .white, location: 0),
                    .init(color: .clear, location: 1)
                ],
                startPoint: .top,
                endPoint: .bottom
            )
            .frame(height: 16)
        }
    }

    // MARK: - Hero Voice Data (mirrors CreateAlarmView.heroVoices)

    private struct HeroVoice {
        let persona: VoicePersona
        let name: String
        let descriptor: String
    }

    private var heroVoices: [HeroVoice] {
        [
            HeroVoice(persona: .calmGuide,        name: "Calm Guide",  descriptor: "Soothing · Gentle"),
            HeroVoice(persona: .energeticCoach,   name: "Coach",       descriptor: "Upbeat · Motivating"),
            HeroVoice(persona: .hardSergeant,     name: "Sergeant",    descriptor: "Firm · Direct"),
            HeroVoice(persona: .evilSpaceLord,    name: "Space Lord",  descriptor: "Dramatic · Commanding"),
            HeroVoice(persona: .playful,          name: "Playful",     descriptor: "Bright · Lighthearted"),
            HeroVoice(persona: .bro,              name: "The Bro",     descriptor: "Casual · Vibes"),
            HeroVoice(persona: .digitalAssistant, name: "Digital",     descriptor: "Robotic · Helpful"),
            HeroVoice(persona: .calmGuide,        name: "Morning Sun", descriptor: "Warm · Optimistic"),
        ]
    }
}

// MARK: - Voice Waveform (shared shape used by CreateAlarmView)

private struct VoiceWaveform: View {

    // MARK: - Constants

    let bands: [CGFloat]
    let isPlaying: Bool

    private let barWidth: CGFloat = 3
    private let barSpacing: CGFloat = 4
    private let minBarHeight: CGFloat = 3
    private let restingHeights: [CGFloat] = (0..<24).map { i in
        let t = CGFloat(i) / 23.0
        let hump = sin(t * .pi)
        return 0.2 + hump * 0.3
    }

    // MARK: - Body

    var body: some View {
        GeometryReader { geo in
            HStack(alignment: .center, spacing: barSpacing) {
                ForEach(0..<bands.count, id: \.self) { i in
                    let amplitude = isPlaying ? max(bands[i], 0.05) : restingHeights[i]
                    let height = max(minBarHeight, amplitude * geo.size.height)

                    Capsule()
                        .fill(.white.opacity(isPlaying ? 0.9 : 0.35))
                        .frame(width: barWidth, height: height)
                        .animation(.easeOut(duration: 0.08), value: amplitude)
                }
            }
            .frame(width: geo.size.width, height: geo.size.height, alignment: .center)
            .animation(.easeInOut(duration: 0.3), value: isPlaying)
        }
    }
}

// MARK: - Previews

#Preview {
    OnboardingContainerView.preview(step: .confirmation)
}
