//
//  SnoozeAlarmIntent.swift
//  Alarmio
//
//  Created by Parenthood ApS on 4/3/26
//  Copyright © 2026 Parenthood ApS. All rights reserved.
//

import AlarmKit
import ActivityKit
import AppIntents
import Foundation
import SwiftUI

/// Fired when the user taps the custom Snooze button on the AlarmKit alert.
///
/// Runs in the main app's process (guaranteed by `LiveActivityIntent`), so
/// iOS wakes the app from a suspended state — even with the device locked
/// — to execute `perform()`. From here we can call AlarmManager directly.
///
/// The cap mechanism: this intent increments `currentSnoozeCount` on the
/// alarm and reschedules. When count reaches maxSnoozes, the scheduler
/// builds the final alert with no secondary button, so the next fire
/// cannot be snoozed.
struct SnoozeAlarmIntent: LiveActivityIntent {
    static var title: LocalizedStringResource = "Snooze Alarm"
    static var openAppWhenRun: Bool = false

    @Parameter(title: "Alarm ID")
    var alarmID: String

    init() {}

    init(alarmID: String) {
        self.alarmID = alarmID
    }

    func perform() async throws -> some IntentResult {
        let tapFmt = DateFormatter()
        tapFmt.dateFormat = "HH:mm:ss.SSS"
        print("[SnoozeAlarmIntent.T] TAP at \(tapFmt.string(from: Date())) for alarmID=\(alarmID)")
        print("[SnoozeAlarmIntent] fired for alarmID=\(alarmID)")

        guard let uuid = UUID(uuidString: alarmID) else {
            print("[SnoozeAlarmIntent] invalid UUID, bailing")
            return .result()
        }

        // Load alarms from the App Group shared defaults. Critical: must
        // use the shared suite, not UserDefaults.standard, because this
        // intent runs in the widget extension's process (different sandbox
        // from the main app). Without the App Group, standard defaults
        // would be empty here.
        guard let data = AppGroup.defaults.data(forKey: AppGroup.alarmConfigurationsKey),
              var alarms = try? JSONDecoder().decode([AlarmConfiguration].self, from: data),
              let index = alarms.firstIndex(where: { $0.id == uuid }) else {
            print("[SnoozeAlarmIntent] alarm not found in App Group defaults")
            return .result()
        }

        var alarm = alarms[index]
        let maxSnoozes = alarm.maxSnoozes
        let currentCount = alarm.currentSnoozeCount ?? 0
        print("[SnoozeAlarmIntent] loaded alarm: count=\(currentCount)/\(maxSnoozes) interval=\(alarm.snoozeInterval)min")

        // 1. Stop the currently ringing alarm.
        do {
            try await AlarmManager.shared.stop(id: uuid)
            print("[SnoozeAlarmIntent] stopped current alarm")
        } catch {
            print("[SnoozeAlarmIntent] stop failed: \(error)")
        }

        // 2. Increment the snooze count and persist BEFORE scheduling.
        let newCount = currentCount + 1
        alarm.currentSnoozeCount = newCount
        alarms[index] = alarm
        if let encoded = try? JSONEncoder().encode(alarms) {
            AppGroup.defaults.set(encoded, forKey: AppGroup.alarmConfigurationsKey)
            print("[SnoozeAlarmIntent] saved updated count=\(newCount)")
        }

        // 3. Schedule the next fire. The Live Activity countdown card
        // should run for the full snooze duration, so we schedule the
        // countdown to start at `now` and set preAlert equal to the
        // snooze interval. AlarmKit then rings the alert at
        // `now + snoozeInterval` automatically when the countdown ends.
        let snoozeSeconds = TimeInterval(alarm.snoozeInterval * 60)
        // Unlimited snooze short-circuits the cap so the snooze button
        // never disappears. Bounded mode counts down from maxSnoozes.
        let snoozesRemaining = alarm.unlimitedSnooze
            ? Int.max
            : max(0, maxSnoozes - newCount)

        // Per-snooze sound: indexed file generated by Composer.
        // Bounded mode: snooze #N plays file _N.
        // Unlimited mode: every snooze plays the loop file _1.
        // Composer writes nonce-suffixed names (alarm_<uuid>_<index>_<nonce>.mp3),
        // so scan the Sounds dir for any file matching the index prefix
        // rather than looking up an exact filename.
        let targetIndex = alarm.unlimitedSnooze ? 1 : newCount
        let prefix = "alarm_\(alarm.id.uuidString)_\(targetIndex)_"

        // Existence check inline — intent runs in widget extension, can't
        // hop to MainActor for AudioFileManager.
        let soundsDir = FileManager.default
            .urls(for: .libraryDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Sounds")
        let soundName: String? = (try? FileManager.default.contentsOfDirectory(atPath: soundsDir.path))?
            .first(where: { $0.hasPrefix(prefix) && $0.hasSuffix(".mp3") })
        print("[SnoozeAlarmIntent] next fire in \(alarm.snoozeInterval)min, snoozesRemaining=\(snoozesRemaining), sound=\(soundName ?? "<system default>") (unlimited=\(alarm.unlimitedSnooze))")

        do {
            try await scheduleNext(
                alarmID: uuid,
                snoozeDurationSeconds: snoozeSeconds,
                snoozesRemaining: snoozesRemaining,
                title: buildTitle(for: alarm),
                soundName: soundName
            )
            print("[SnoozeAlarmIntent] next alarm scheduled successfully with sound=\(soundName ?? "<system default>")")
        } catch {
            let ns = error as NSError
            print("[SnoozeAlarmIntent] next schedule failed: \(error)")
            print("[SnoozeAlarmIntent.ERR] domain=\(ns.domain) code=\(ns.code)")
            print("[SnoozeAlarmIntent.ERR] localizedDescription=\(ns.localizedDescription)")
            print("[SnoozeAlarmIntent.ERR] debugDescription=\(ns.debugDescription)")
            print("[SnoozeAlarmIntent.ERR] userInfo=\(ns.userInfo)")
            if let underlying = ns.userInfo[NSUnderlyingErrorKey] as? NSError {
                print("[SnoozeAlarmIntent.ERR] underlying: domain=\(underlying.domain) code=\(underlying.code) desc=\(underlying.localizedDescription) userInfo=\(underlying.userInfo)")
            }
        }

        return .result()
    }

    // MARK: - Private

    private func scheduleNext(
        alarmID: UUID,
        snoozeDurationSeconds: TimeInterval,
        snoozesRemaining: Int,
        title: LocalizedStringResource,
        soundName: String?
    ) async throws {
        let stopButton = AlarmButton(
            text: "STOP",
            textColor: .red,
            systemImageName: "stop.circle.fill"
        )

        let alert: AlarmPresentation.Alert
        let secondaryIntent: (any LiveActivityIntent)?

        if snoozesRemaining > 0 {
            let snoozeButton = AlarmButton(
                text: "SNOOZE",
                textColor: .black,
                systemImageName: "zzz"
            )
            alert = AlarmPresentation.Alert(
                title: title,
                stopButton: stopButton,
                secondaryButton: snoozeButton,
                secondaryButtonBehavior: .custom
            )
            secondaryIntent = SnoozeAlarmIntent(alarmID: alarmID.uuidString)
        } else {
            alert = AlarmPresentation.Alert(
                title: title,
                stopButton: stopButton
            )
            secondaryIntent = nil
        }

        // Diagnostic phase. Start at 1 (minimum config), add a layer,
        // rebuild, test. First phase that throws Code=0 identifies the
        // culprit. Phases:
        //   1: bare alert, .fixed(now+65s), no countdown, no secondary, default sound
        //   2: +  .fixed(now+3s) with preAlert=62s, still no countdown presentation
        //   3: + AlarmPresentation.Countdown in presentation
        //   4: + secondaryIntent
        //   5: + custom sound (.named(soundName))
        //   6: phase 1 (no countdown / no Live Activity) + secondaryIntent + custom sound
        let phase: Int = 6

        let fmt = DateFormatter()
        fmt.dateFormat = "HH:mm:ss.SSS"

        let schedulingBuffer: TimeInterval = 3
        let effectiveSnooze = max(snoozeDurationSeconds, 60) // enforce ≥60s
        let countdownStart = Date().addingTimeInterval(schedulingBuffer)
        let preAlertSeconds = max(1, effectiveSnooze - schedulingBuffer)
        let bareFireDate = Date().addingTimeInterval(effectiveSnooze + schedulingBuffer)

        // Build presentation per phase.
        let presentation: AlarmPresentation
        if phase >= 3 {
            let countdownContent = AlarmPresentation.Countdown(
                title: "Alarm ringing soon",
                pauseButton: AlarmButton(
                    text: "Skip",
                    textColor: .white,
                    systemImageName: "forward.fill"
                )
            )
            presentation = AlarmPresentation(alert: alert, countdown: countdownContent)
        } else {
            presentation = AlarmPresentation(alert: alert)
        }

        let attributes = AlarmAttributes<AlarmioMetadata>(
            presentation: presentation,
            tintColor: .blue
        )

        // countdownDuration + schedule varies by phase.
        let countdownDuration: Alarm.CountdownDuration?
        let schedule: Alarm.Schedule
        switch phase {
        case 1:
            countdownDuration = nil
            schedule = .fixed(bareFireDate)
        default:
            countdownDuration = .init(preAlert: preAlertSeconds, postAlert: nil)
            schedule = .fixed(countdownStart)
        }

        // secondaryIntent per phase.
        let phaseSecondaryIntent: (any LiveActivityIntent)? = phase >= 4 ? secondaryIntent : nil

        // sound per phase.
        let phaseSound: AlertConfiguration.AlertSound
        if phase >= 5, let name = soundName {
            phaseSound = .named(name)
        } else {
            phaseSound = .default
        }

        let config = AlarmManager.AlarmConfiguration<AlarmioMetadata>(
            countdownDuration: countdownDuration,
            schedule: schedule,
            attributes: attributes,
            stopIntent: StopAlarmIntent(alarmID: alarmID.uuidString),
            secondaryIntent: phaseSecondaryIntent,
            sound: phaseSound
        )

        let preCallDate = Date()
        print("[SnoozeAlarmIntent.PHASE] phase=\(phase) preSchedule=\(fmt.string(from: preCallDate))")
        print("[SnoozeAlarmIntent.CFG] hasCountdownPresentation=\(phase >= 3) hasSecondaryIntent=\(phaseSecondaryIntent != nil) soundIsDefault=\(phase < 5 || soundName == nil) countdownDuration.preAlert=\(countdownDuration?.preAlert ?? -1) scheduleFireDate=\(fmt.string(from: phase == 1 ? bareFireDate : countdownStart))")
        print("[SnoozeAlarmIntent.AUTH] extensionAuthState=\(AlarmManager.shared.authorizationState)")

        // Defensive: ensure the previous alarm slot is fully released
        // before scheduling with the same UUID. Sometimes AlarmKit's
        // stop() returns before alarmd has finished tearing down the
        // record, and schedule() with the same UUID throws Code=0.
        try? AlarmManager.shared.cancel(id: alarmID)
        try? await Task.sleep(nanoseconds: 200_000_000)  // 200ms
        print("[SnoozeAlarmIntent.T] cancelled + slept 200ms, scheduling now")

        _ = try await AlarmManager.shared.schedule(id: alarmID, configuration: config)

        let postCallDate = Date()
        print("[SnoozeAlarmIntent.T] phase=\(phase) postSchedule=\(fmt.string(from: postCallDate)) schedCallTook=\(Int(postCallDate.timeIntervalSince(preCallDate) * 1000))ms")
    }

    private func buildTitle(for alarm: AlarmConfiguration) -> LocalizedStringResource {
        if let tone = alarm.tone {
            let toneLabel = switch tone {
            case .calm: "Calm"
            case .encourage: "Encouraging"
            case .push: "Motivating"
            case .strict: "Strict"
            case .fun: "Fun"
            case .other: "Custom"
            }
            return "\(toneLabel) Wake Up"
        }
        return "Wake Up"
    }
}
